# This is a basic workflow to help you get started with Actions

name: CI CD Flask APP to AWS Elasticbeanstalk 


# events but only for the master branch
env:
  EB_PACKEGE_S3_BACKET_NAME: "my-flask-app-ci-cd-github-actions"
  DEPLOY_PACKEGE_NAME      : "My-flask-app-${{github.sha}}.zip"
  APP_NAME: "My-flask-app"
  ENV_NAME: "MyFlaskApp-env"
  AWS_REGION: "eu-central-1"  

on:
  push:
    branches: 
      - master
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Ci-job-1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Clone REPO 
      uses: actions/checkout@v2
    
    - name: Create zip-file for EB
      run : zip -r ${{env.DEPLOY_PACKEGE_NAME}} ./ -x *.git*
                          
    - name: AWS configure
      uses: aws-actions/configure-aws-credentials/@v1
      with:
       aws-access-key-id : ${{secrets.ACCESS_KEY_ID}}
       aws-secret-access-key : ${{secrets.SECRET_ACCESS_KEY}}
       aws-region: ${{ env.AWS_REGION}}
              
    - name: Copy ZIP to S3
      run: aws s3 cp ${{env.DEPLOY_PACKEGE_NAME}}  s3://${{env.EB_PACKEGE_S3_BACKET_NAME}}
      
    - name: Print OK message 
      run: echo "ZIP packege copied successfully" 
#All steps follow are  CD steps    
    - name: Create a new EV version
      run: |
       aws elasticbeanstalk create-application-version\
       --application-name ${{env.APP_NAME}}\
       --source-bundle S3Bucket=${{env.EB_PACKEGE_S3_BACKET_NAME}},S3Key=${{env.DEPLOY_PACKEGE_NAME}}\
       --version-label "Ver-${{ github.sha }}" \
       --description "CommitSHA-${{ github.sha }}"  
     
    - name:  Deploy new version APP to EB
      run: |
        aws elasticbeanstalk update-environment \
        --environment-name ${{env.ENV_NAME}}\
        --version-label  "Ver-${{ github.sha }}"
      
  
